on: push

jobs:
  assess-policy-compliance:    
    runs-on: ubuntu-latest
    steps:
    # Azure Login       
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}} 
    
    - name: Check for resource compliance
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
          /subscriptions/fffb0c65-e90a-4b5d-adac-a5d6d399e2cc
        scopes-ignore: |
          /subscriptions/fffb0c65-e90a-4b5d-adac-a5d6d399e2cc
