on: push

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted

  run-depoyment:    
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
    # Azure Login       
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}} 
    
    - name: Azure PowerShell Action
      uses: Azure/powershell@v1
      with:
        # Specify the Az PowerShell script here.
        inlineScript: 
          Select-AzSubscription fffb0c65-e90a-4b5d-adac-a5d6d399e2cc
          New-AzResourceGroup -Name Dev-Pels-02 -Location "West Europe" 
        # Azure PS version to be used to execute the script, example: 1.8.0, 2.8.0, 3.4.0. To use the latest version, specify "latest".
        azPSVersion: 
          latest
        errorActionPreference:
          Stop
        failOnStandardError:
          false
    
    - name: Check for resource compliance
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
          /subscriptions/fffb0c65-e90a-4b5d-adac-a5d6d399e2cc
        scopes-ignore: |
          /subscriptions/fffb0c65-e90a-4b5d-adac-a5d6d399e2cc
