on: push

env:
  resourceGroupName: Dev-Pels-01
  bicepfilePath: main.bicep

jobs:
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted

  run-deployment:    
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
    # Azure Login       
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true

    # Deploy Resource Group
    - name: Create Resource Group
      uses: Azure/powershell@v1
      with:
        inlineScript: |
          Select-AzSubscription fffb0c65-e90a-4b5d-adac-a5d6d399e2cc
          New-AzResourceGroup -Name Dev-Pels-02 -Location "West Europe" -Force
        azPSVersion: 
          latest

  Compliancy-Scan:
    runs-on: ubuntu-latest
    needs: run-deployment
    steps:
    - name: Check for resource compliance
      uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
          /subscriptions/fffb0c65-e90a-4b5d-adac-a5d6d399e2cc
